version: "3.8"

services:
  django_gunicorn:
    volumes:
      - static:/static
    build:
      context: .
    ports:
      - "8000:8080"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
    - "80:80"
    depends_on:
      - django_gunicorn


volumes:
  static: